# Generated by Django 5.1.1 on 2024-10-17 21:27

import os
from dotenv import load_dotenv
from django.db import migrations
from django.contrib.auth import get_user_model

def create_users(apps, schema_editor):
    User = get_user_model()
    load_dotenv()
    password = os.environ.get('ALUNO_PWD')
    username = 'aluno-meadapt'
    email = 'aluno-meadapt@meadapt.com'

    if not User.objects.filter(username=username).exists():
            User.objects.create_superuser(
                username=username,
                password=password,
                email=email
            )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]