name: Supabase call

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Call supabase
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        pip install -r requirements.txt
        python scripts/supabase_api.py
    - name: Workflow failure notification
      uses: JasonEtco/create-an-issue@v2
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        filename: .github/supabase_workflow_failure.md
